language: go
dist: trusty
sudo: false

matrix:
  include:
    - go: 1.8.3
    - go: 1.9
    - go: tip
  allow_failures:
    - go: tip

branches:
    only:
        - master
        - dev

script:
    - git clone https://github.com/Bytom/bytom.git $GOPATH/src/github.com/bytom
    - cd $GOPATH/src/github.com/bytom
    - make test
